steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'APP_ENV',
        '--build-arg',
        'CORS_ORIGIN',
        '--build-arg',
        'DB_HOST',
        '--build-arg',
        'DB_PORT',
        '--build-arg',
        'DB_USERNAME',
        '--build-arg',
        'DB_PASSWORD',
        '--build-arg',
        'DB_DATABASE',
        '--build-arg',
        'DB_SYNC',
        '--build-arg',
        'FIREBASE_PRIVATE_KEY',
        '--build-arg',
        'FIREBASE_CLIENT_EMAIL',
        '--build-arg',
        'FIREBASE_PROJECT_ID',
        '--build-arg',
        'CHAIN_ID',
        '--build-arg',
        'SPACE_NAME',
        '-t',
        'gcr.io/${PROJECT_ID}/app-notification-server:$SHORT_SHA',
        '.',
      ]

    secretEnv:
      [
        'APP_ENV',
        'CORS_ORIGIN',
        'DB_HOST',
        'DB_PORT',
        'DB_USERNAME',
        'DB_PASSWORD',
        'DB_DATABASE',
        'DB_SYNC',
        'FIREBASE_PRIVATE_KEY',
        'FIREBASE_CLIENT_EMAIL',
        'FIREBASE_PROJECT_ID',
        'CHAIN_ID',
        'SPACE_NAME',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/app-notification-server:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-notification-server'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/app-notification-server:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'

timeout: 1200s

images:
  - gcr.io/${PROJECT_ID}/app-notification-server:$SHORT_SHA
options:
  machineType: 'E2_HIGHCPU_8'

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_APP_ENV/versions/latest
      env: APP_ENV
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_CORS_ORIGIN/versions/latest
      env: CORS_ORIGIN
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_DB_HOST/versions/latest
      env: DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_DB_PORT/versions/latest
      env: DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_DB_USERNAME/versions/latest
      env: DB_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_DB_DATABASE/versions/latest
      env: DB_DATABASE
    - versionName: projects/${PROJECT_ID}/secrets/NOTIFICATION_DB_SYNC/versions/latest
      env: DB_SYNC
    - versionName: projects/${PROJECT_ID}/secrets/TEST_SPORTBOOK_JOB_FIREBASE_PROJECT_ID/versions/latest
      env: FIREBASE_PROJECT_ID
    - versionName: projects/${PROJECT_ID}/secrets/TEST_SPORTBOOK_JOB_FIREBASE_PRIVATE_KEY/versions/latest
      env: FIREBASE_PRIVATE_KEY
    - versionName: projects/${PROJECT_ID}/secrets/TEST_SPORTBOOK_JOB_FIREBASE_CLIENT_EMAIL/versions/latest
      env: FIREBASE_CLIENT_EMAIL
    - versionName: projects/${PROJECT_ID}/secrets/TEST_SPORTBOOK_JOB_CHAIN_ID/versions/latest
      env: CHAIN_ID
    - versionName: projects/${PROJECT_ID}/secrets/TEST_SPORTBOOK_JOB_APP_NAME/versions/latest
      env: SPACE_NAME
