version: "3.8"
services:
  app:
    image: app-server:1.0.0-dev
    container_name: app-server-dev
    build:
      context: .
      dockerfile: docker/nest/dev.dockerfile
    working_dir: /home/node/workspace
    command: npm run start:debug
    restart: unless-stopped
    tty: true
    volumes:
      - .:/home/node/workspace
      - /home/node/workspace/node_modules
    networks:
      -  app-server-network
    env_file:
      - .env.dev
    ports:
      - '8016:8003'
      - '80:80'

  redis:
    container_name: app-redis
    image: redis
    restart: unless-stopped
    ports:
      - 6383:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - app-server-network
    volumes:
      - app-redis:/data

  database:
    container_name: app-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - app-database:/var/lib/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5437:5432
    networks:
      - app-server-network

  timescale-database:
    container_name: app-timescale-database
    image: timescale/timescaledb-ha:pg14-latest
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - app-timescale-database:/var/lib/postgresql/data
      - ./docker/timescaleDB:/docker-entrypoint-initdb.d
    environment:
      # TIMESCALEDB_TELEMETRY: on
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      PGPORT: 5433
    ports:
      - 5438:5433
    networks:
      - app-server-network


networks:
  app-server-network:
    driver: bridge

volumes:
  app-redis:
    driver: local
  app-database:
    driver: local
  app-timescale-database:
    driver: local
    
# https://docs.timescale.com/self-hosted/latest/install/installation-docker/

# psql -U root -h localhost
# \c app_timescale
# CREATE EXTENSION IF NOT EXISTS timescaledb;
# psql -U root -h localhost -d app_timescale
# \dx
# select create_hypertable('prices','time');
# drop table prices;