# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
# https://github.com/searxng/searxng/blob/master/searx/settings.yml
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: 'myscretkey' # change ultrasecretkey -> ...!
  limiter: false # can be disabled for a private instance
  image_proxy: true
search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "yandex", "mwmbl",
  # "seznam", "startpage", "stract", "swisscows", "qwant", "wikipedia" - leave blank to turn it off
  # by default.
  autocomplete: 'google'
  # minimun characters to type before autocompleter starts
  autocomplete_min: 4
  formats:
    - html
    - json
ui:
  static_use_hash: false
redis:
  url: redis://redis:6379/0
